 version:  '3.7'
 services:

   db:
     image: mysql:8.0
     restart: on-failure
     command: --default-authentication-plugin=mysql_native_password
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
     volumes:
       - ./db_data:/var/lib/mysql:rw
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

   php:
     build:
       context: .
       dockerfile: docker/php/Dockerfile
     restart: on-failure
     env_file:
       - .env
     volumes:
       - './apps/match-app/:/usr/src/app/'
     ports:
       - '${PHP_PORT}:8000'

   adminer:
     image: adminer
     restart: on-failure
     ports:
       - '${ADMINER_PORT}:8080'

   nginx:
     image: nginx
     restart: on-failure
     volumes:
       - './apps/match-app/public/:/usr/src/app/'
       - './nginx.conf:/etc/nginx/conf.d/default.conf:ro'
     ports:
       - '${NGINX_PORT}:80'
     depends_on:
       - php
